// Code generated by ./cmd/gen - DO NOT EDIT.

package static

const AppleTouchIconPng string = "/static/apple-touch-icon-4de2c156ea99.png"
const MainCss string = "/static/main-67353a3a089c.css"
const FaviconIco string = "/static/favicon-39b06fd9dbf6.ico"
const Icon192Png string = "/static/icon-192-549202b65a25.png"
const Icon512Png string = "/static/icon-512-241df592b09a.png"
const IconSvg string = "/static/icon-224249180cef.svg"
